import test_project_edt
import test_project_edt_reprogramar
import test_project_task
import test_project_project
import test_project_task_registro_progreso
# Pruebas NO actualizadas
#import test_project_task_pendiente
#import test_project_predecesor
#import test_domain_project_group_project_user
#import test_domain_project_edt_idu_group_project_user_externo
#import test_domain_project_group_project_manager
#import test_workflow_task_reporte_avance
